import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:path_provider/path_provider.dart';
import '../models/app_model.dart';

/// APP 存储管理服务
class AppService {
  static final AppService _instance = AppService._internal();
  factory AppService() => _instance;
  AppService._internal();

  List<CustomApp> _apps = [];
  bool _isLoaded = false;

  /// 获取所有自定义 APP
  List<CustomApp> get allApps => List.unmodifiable(_apps);

  /// 初始化
  Future<void> init() async {
    await _loadApps();
  }

  /// 加载 APP 列表
  Future<void> _loadApps() async {
    try {
      final dir = await _getAppStorageDir();
      final file = File('${dir.path}/custom_apps.json');
      if (await file.exists()) {
        final content = await file.readAsString();
        final List<dynamic> data = json.decode(content);
        _apps = data.map((json) => CustomApp.fromJson(json)).toList();
      }
      _isLoaded = true;
    } catch (e) {
      debugPrint('加载APP列表失败: $e');
    }
  }

  /// 保存 APP 列表
  Future<void> _saveApps() async {
    try {
      final dir = await _getAppStorageDir();
      if (!await dir.exists()) {
        await dir.create(recursive: true);
      }
      final file = File('${dir.path}/custom_apps.json');
      final data = _apps.map((app) => app.toJson()).toList();
      await file.writeAsString(json.encode(data));
    } catch (e) {
      debugPrint('保存APP列表失败: $e');
    }
  }

  /// 获取存储目录
  Future<Directory> _getAppStorageDir() async {
    final appDir = await getApplicationDocumentsDirectory();
    return Directory('${appDir.path}/custom_apps');
  }

  /// 添加新 APP
  Future<CustomApp> addApp({
    required String name,
    required String url,
    required String iconName,
    required String iconColor,
    String description = '',
    String? injectCSS,
    String? injectJS,
  }) async {
    final id = 'app_${DateTime.now().millisecondsSinceEpoch}';
    final packageName = 'com.allinbox.app$id';

    final app = CustomApp(
      id: id,
      name: name,
      url: url,
      iconName: iconName,
      iconColor: iconColor,
      description: description,
      packageName: packageName,
      injectCSS: injectCSS,
      injectJS: injectJS,
      createdAt: DateTime.now(),
    );

    _apps.add(app);
    await _saveApps();
    return app;
  }

  /// 更新 APP
  Future<void> updateApp(CustomApp updatedApp) async {
    final index = _apps.indexWhere((a) => a.id == updatedApp.id);
    if (index != -1) {
      _apps[index] = updatedApp;
      await _saveApps();
    }
  }

  /// 删除 APP
  Future<void> deleteApp(String id) async {
    // 删除 APK 文件（如果有）
    final app = _apps.firstWhere((a) => a.id == id);
    if (app.apkPath != null) {
      try {
        final apkFile = File(app.apkPath!);
        if (await apkFile.exists()) {
          await apkFile.delete();
        }
      } catch (_) {}
    }

    _apps.removeWhere((a) => a.id == id);
    await _saveApps();
  }

  /// 标记 APP 为已编译
  Future<void> markAsBuilt(String id, String apkPath) async {
    final index = _apps.indexWhere((a) => a.id == id);
    if (index != -1) {
      _apps[index] = _apps[index].copyWith(isBuilt: true, apkPath: apkPath);
      await _saveApps();
    }
  }

  /// 获取 APP 的编译输出目录
  Future<Directory> _getBuildOutputDir(String appId) async {
    final dir = await _getAppStorageDir();
    return Directory('${dir.path}/build_output/$appId');
  }

  /// 创建项目文件结构
  Future<Directory> createProjectFiles(CustomApp app) async {
    final outputDir = await _getBuildOutputDir(app.id);
    if (await outputDir.exists()) {
      await outputDir.delete(recursive: true);
    }
    await outputDir.create(recursive: true);

    // 创建 pubspec.yaml
    await _writePubspec(outputDir, app);
    
    // 创建 lib/main.dart
    await _writeMainDart(outputDir, app);
    
    // 创建 AndroidManifest.xml 模板
    await _writeAndroidManifest(outputDir, app);

    return outputDir;
  }

  /// 写入 pubspec.yaml
  Future<void> _writePubspec(Directory dir, CustomApp app) async {
    final content = '''
name: ${app.packageName.replaceAll('.', '_')}
description: ${app.name} - Generated by ALL IN BOX
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
''';
    await File('${dir.path}/pubspec.yaml').writeAsString(content);
  }

  /// 写入 main.dart
  Future<void> _writeMainDart(Directory dir, CustomApp app) async {
    final injectCSS = app.injectCSS ?? '';
    final injectJS = app.injectJS ?? '';
    
    final content = '''
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

void main() {
  runApp(const MyGeneratedApp());
}

class MyGeneratedApp extends StatelessWidget {
  const MyGeneratedApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: '${app.name}',
      debugShowCheckedModeBanner: false,
      theme: ThemeData(
        colorSchemeSeed: Color(${app.iconColor.replaceAll('#', '0xFF')}),
        useMaterial3: true,
      ),
      home: const WebViewApp(),
    );
  }
}

class WebViewApp extends StatefulWidget {
  const WebViewApp({super.key});

  @override
  State<WebViewApp> createState() => _WebViewAppState();
}

class _WebViewAppState extends State<WebViewApp> {
  late final WebViewController _controller;
  bool _isLoading = true;
  double _progress = 0;

  @override
  void initState() {
    super.initState();
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setNavigationDelegate(
        NavigationDelegate(
          onProgress: (int progress) {
            setState(() => _progress = progress / 100);
            if (progress == 100) {
              setState(() => _isLoading = false);
            }
          },
          onPageStarted: (String url) {
            setState(() => _isLoading = true);
          },
          onPageFinished: (String url) {
            setState(() => _isLoading = false);
          },
        ),
      )
      ..loadRequest(Uri.parse('${app.url}'));
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('${app.name}'),
        centerTitle: true,
        bottom: _isLoading
            ? PreferredSize(
                preferredSize: const Size.fromHeight(3),
                child: LinearProgressIndicator(value: _progress),
              )
            : null,
      ),
      body: WebViewWidget(controller: _controller),
    );
  }
}
''';
    await File('${dir.path}/lib/main.dart').writeAsString(content);
  }

  /// 写入 AndroidManifest.xml 模板
  Future<void> _writeAndroidManifest(Directory dir, CustomApp app) async {
    final content = '''
<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="${app.packageName}">
    <uses-permission android:name="android.permission.INTERNET"/>
    <application
        android:label="${app.name}"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:exported="true"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|smallestScreenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true">
            <meta-data
                android:name="io.flutter.embedding.android.NormalTheme"
                android:resource="@style/NormalTheme"/>
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
        <meta-data
            android:name="flutterEmbedding"
            android:value="2"/>
    </application>
</manifest>
''';
    await File('${dir.path}/android/app/src/main/AndroidManifest.xml').writeAsString(content);
  }
}
